baseurl = "/"
#baseurl = "/data/Dropbox/chrisgreenley.com/blog/public/"
title = "Chris Greenley"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
newContentEditor = "vim"
pygmentsStyle = "manni"
PygmentsCodeFences = 'true'
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-114541825-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Projects relating to embedded/computer engineering, electrical engineering, 3D printing, physics, etc..."
  copyright = "&copy;2020 Chris Greenley"
  sidebarAbout = [
    "I am a physicist and engineer with a passion for understanding the universe and building new things.",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Project Posts"
  url = "projects/"

  [[params.navlinks]]
  name = "Blog Posts"
  url = "blog/"

#  [[params.navlinks]]
#  name = "Get in touch"
#  url = "contact/"

  [params.social]
#  email         = ""
  linkedin      = "https://www.linkedin.com/in/cgreenley/"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
  github        = "https://github.com/FerriteGiant"
  thingiverse = "https://www.thingiverse.com/FerriteGiant/designs"
  instructables = "https://www.instructables.com/member/FerriteGiant/instructables/"
